version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chatting
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: 1234
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6380:6379"
#    volumes:
#      - redis_data:/data
#
#volumes:
#  mariadb_data:
#  redis_data:
